In [13]:
import requests
import pandas as pd

In [15]:
baseurl = "https://rickandmortyapi.com/api/"

endpoint = 'character'
r = requests.get(baseurl + endpoint)
r

In [ ]:
r.json()

{'info': {'count': 826,
  'pages': 42,
  'next': 'https://rickandmortyapi.com/api/character?page=2',
  'prev': None},
 'results': [{'id': 1,
   'name': 'Rick Sanchez',
   'status': 'Alive',
   'species': 'Human',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'Earth (C-137)',
    'url': 'https://rickandmortyapi.com/api/location/1'},
   'location': {'name': 'Citadel of Ricks',
    'url': 'https://rickandmortyapi.com/api/location/3'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/1',
    'https://rickandmortyapi.com/api/episode/2',
    'https://rickandmortyapi.com/api/episode/3',
    'https://rickandmortyapi.com/api/episode/4',
    'https://rickandmortyapi.com/api/episode/5',
    'https://rickandmortyapi.com/api/episode/6',
    'https://rickandmortyapi.com/api/episode/7',
    'https://rickandmortyapi.com/api/episode/8',
    'https://rickandmortyapi.com/api/episode/9',
    'https://rickandmortyapi.com/api/episode/10',
    'https://rickandmortyapi.com/api/episode/11',
    'https://rickandmortyapi.com/api/episode/12',
    'https://rickandmortyapi.com/api/episode/13',
    'https://rickandmortyapi.com/api/episode/14',
    'https://rickandmortyapi.com/api/episode/15',
    'https://rickandmortyapi.com/api/episode/16',
    'https://rickandmortyapi.com/api/episode/17',
    'https://rickandmortyapi.com/api/episode/18',
    'https://rickandmortyapi.com/api/episode/19',
    'https://rickandmortyapi.com/api/episode/20',
    'https://rickandmortyapi.com/api/episode/21',
    'https://rickandmortyapi.com/api/episode/22',
    'https://rickandmortyapi.com/api/episode/23',
    'https://rickandmortyapi.com/api/episode/24',
    'https://rickandmortyapi.com/api/episode/25',
    'https://rickandmortyapi.com/api/episode/26',
    'https://rickandmortyapi.com/api/episode/27',
    'https://rickandmortyapi.com/api/episode/28',
    'https://rickandmortyapi.com/api/episode/29',
    'https://rickandmortyapi.com/api/episode/30',
    'https://rickandmortyapi.com/api/episode/31',
    'https://rickandmortyapi.com/api/episode/32',
    'https://rickandmortyapi.com/api/episode/33',
    'https://rickandmortyapi.com/api/episode/34',
    'https://rickandmortyapi.com/api/episode/35',
    'https://rickandmortyapi.com/api/episode/36',
    'https://rickandmortyapi.com/api/episode/37',
    'https://rickandmortyapi.com/api/episode/38',
    'https://rickandmortyapi.com/api/episode/39',
    'https://rickandmortyapi.com/api/episode/40',
    'https://rickandmortyapi.com/api/episode/41',
    'https://rickandmortyapi.com/api/episode/42',
    'https://rickandmortyapi.com/api/episode/43',
    'https://rickandmortyapi.com/api/episode/44',
    'https://rickandmortyapi.com/api/episode/45',
    'https://rickandmortyapi.com/api/episode/46',
    'https://rickandmortyapi.com/api/episode/47',
    'https://rickandmortyapi.com/api/episode/48',
    'https://rickandmortyapi.com/api/episode/49',
    'https://rickandmortyapi.com/api/episode/50',
    'https://rickandmortyapi.com/api/episode/51'],
   'url': 'https://rickandmortyapi.com/api/character/1',
   'created': '2017-11-04T18:48:46.250Z'},
  {'id': 2,
   'name': 'Morty Smith',
   'status': 'Alive',
   'species': 'Human',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Citadel of Ricks',
    'url': 'https://rickandmortyapi.com/api/location/3'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/1',
    'https://rickandmortyapi.com/api/episode/2',
    'https://rickandmortyapi.com/api/episode/3',
    'https://rickandmortyapi.com/api/episode/4',
    'https://rickandmortyapi.com/api/episode/5',
    'https://rickandmortyapi.com/api/episode/6',
    'https://rickandmortyapi.com/api/episode/7',
    'https://rickandmortyapi.com/api/episode/8',
    'https://rickandmortyapi.com/api/episode/9',
    'https://rickandmortyapi.com/api/episode/10',
    'https://rickandmortyapi.com/api/episode/11',
    'https://rickandmortyapi.com/api/episode/12',
    'https://rickandmortyapi.com/api/episode/13',
    'https://rickandmortyapi.com/api/episode/14',
    'https://rickandmortyapi.com/api/episode/15',
    'https://rickandmortyapi.com/api/episode/16',
    'https://rickandmortyapi.com/api/episode/17',
    'https://rickandmortyapi.com/api/episode/18',
    'https://rickandmortyapi.com/api/episode/19',
    'https://rickandmortyapi.com/api/episode/20',
    'https://rickandmortyapi.com/api/episode/21',
    'https://rickandmortyapi.com/api/episode/22',
    'https://rickandmortyapi.com/api/episode/23',
    'https://rickandmortyapi.com/api/episode/24',
    'https://rickandmortyapi.com/api/episode/25',
    'https://rickandmortyapi.com/api/episode/26',
    'https://rickandmortyapi.com/api/episode/27',
    'https://rickandmortyapi.com/api/episode/28',
    'https://rickandmortyapi.com/api/episode/29',
    'https://rickandmortyapi.com/api/episode/30',
    'https://rickandmortyapi.com/api/episode/31',
    'https://rickandmortyapi.com/api/episode/32',
    'https://rickandmortyapi.com/api/episode/33',
    'https://rickandmortyapi.com/api/episode/34',
    'https://rickandmortyapi.com/api/episode/35',
    'https://rickandmortyapi.com/api/episode/36',
    'https://rickandmortyapi.com/api/episode/37',
    'https://rickandmortyapi.com/api/episode/38',
    'https://rickandmortyapi.com/api/episode/39',
    'https://rickandmortyapi.com/api/episode/40',
    'https://rickandmortyapi.com/api/episode/41',
    'https://rickandmortyapi.com/api/episode/42',
    'https://rickandmortyapi.com/api/episode/43',
    'https://rickandmortyapi.com/api/episode/44',
    'https://rickandmortyapi.com/api/episode/45',
    'https://rickandmortyapi.com/api/episode/46',
    'https://rickandmortyapi.com/api/episode/47',
    'https://rickandmortyapi.com/api/episode/48',
    'https://rickandmortyapi.com/api/episode/49',
    'https://rickandmortyapi.com/api/episode/50',
    'https://rickandmortyapi.com/api/episode/51'],
   'url': 'https://rickandmortyapi.com/api/character/2',
   'created': '2017-11-04T18:50:21.651Z'},
  {'id': 3,
   'name': 'Summer Smith',
   'status': 'Alive',
   'species': 'Human',
   'type': '',
   'gender': 'Female',
   'origin': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'location': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/6',
    'https://rickandmortyapi.com/api/episode/7',
    'https://rickandmortyapi.com/api/episode/8',
    'https://rickandmortyapi.com/api/episode/9',
    'https://rickandmortyapi.com/api/episode/10',
    'https://rickandmortyapi.com/api/episode/11',
    'https://rickandmortyapi.com/api/episode/12',
    'https://rickandmortyapi.com/api/episode/14',
    'https://rickandmortyapi.com/api/episode/15',
    'https://rickandmortyapi.com/api/episode/16',
    'https://rickandmortyapi.com/api/episode/17',
    'https://rickandmortyapi.com/api/episode/18',
    'https://rickandmortyapi.com/api/episode/19',
    'https://rickandmortyapi.com/api/episode/20',
    'https://rickandmortyapi.com/api/episode/21',
    'https://rickandmortyapi.com/api/episode/22',
    'https://rickandmortyapi.com/api/episode/23',
    'https://rickandmortyapi.com/api/episode/24',
    'https://rickandmortyapi.com/api/episode/25',
    'https://rickandmortyapi.com/api/episode/26',
    'https://rickandmortyapi.com/api/episode/27',
    'https://rickandmortyapi.com/api/episode/29',
    'https://rickandmortyapi.com/api/episode/30',
    'https://rickandmortyapi.com/api/episode/31',
    'https://rickandmortyapi.com/api/episode/32',
    'https://rickandmortyapi.com/api/episode/33',
    'https://rickandmortyapi.com/api/episode/34',
    'https://rickandmortyapi.com/api/episode/35',
    'https://rickandmortyapi.com/api/episode/36',
    'https://rickandmortyapi.com/api/episode/38',
    'https://rickandmortyapi.com/api/episode/39',
    'https://rickandmortyapi.com/api/episode/40',
    'https://rickandmortyapi.com/api/episode/41',
    'https://rickandmortyapi.com/api/episode/42',
    'https://rickandmortyapi.com/api/episode/43',
    'https://rickandmortyapi.com/api/episode/44',
    'https://rickandmortyapi.com/api/episode/45',
    'https://rickandmortyapi.com/api/episode/46',
    'https://rickandmortyapi.com/api/episode/47',
    'https://rickandmortyapi.com/api/episode/48',
    'https://rickandmortyapi.com/api/episode/49',
    'https://rickandmortyapi.com/api/episode/51'],
   'url': 'https://rickandmortyapi.com/api/character/3',
   'created': '2017-11-04T19:09:56.428Z'},
  {'id': 4,
   'name': 'Beth Smith',
   'status': 'Alive',
   'species': 'Human',
   'type': '',
   'gender': 'Female',
   'origin': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'location': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/6',
    'https://rickandmortyapi.com/api/episode/7',
    'https://rickandmortyapi.com/api/episode/8',
    'https://rickandmortyapi.com/api/episode/9',
    'https://rickandmortyapi.com/api/episode/10',
    'https://rickandmortyapi.com/api/episode/11',
    'https://rickandmortyapi.com/api/episode/12',
    'https://rickandmortyapi.com/api/episode/14',
    'https://rickandmortyapi.com/api/episode/15',
    'https://rickandmortyapi.com/api/episode/16',
    'https://rickandmortyapi.com/api/episode/18',
    'https://rickandmortyapi.com/api/episode/19',
    'https://rickandmortyapi.com/api/episode/20',
    'https://rickandmortyapi.com/api/episode/21',
    'https://rickandmortyapi.com/api/episode/22',
    'https://rickandmortyapi.com/api/episode/23',
    'https://rickandmortyapi.com/api/episode/24',
    'https://rickandmortyapi.com/api/episode/25',
    'https://rickandmortyapi.com/api/episode/26',
    'https://rickandmortyapi.com/api/episode/27',
    'https://rickandmortyapi.com/api/episode/28',
    'https://rickandmortyapi.com/api/episode/29',
    'https://rickandmortyapi.com/api/episode/30',
    'https://rickandmortyapi.com/api/episode/31',
    'https://rickandmortyapi.com/api/episode/32',
    'https://rickandmortyapi.com/api/episode/33',
    'https://rickandmortyapi.com/api/episode/34',
    'https://rickandmortyapi.com/api/episode/35',
    'https://rickandmortyapi.com/api/episode/36',
    'https://rickandmortyapi.com/api/episode/38',
    'https://rickandmortyapi.com/api/episode/39',
    'https://rickandmortyapi.com/api/episode/40',
    'https://rickandmortyapi.com/api/episode/41',
    'https://rickandmortyapi.com/api/episode/42',
    'https://rickandmortyapi.com/api/episode/43',
    'https://rickandmortyapi.com/api/episode/44',
    'https://rickandmortyapi.com/api/episode/45',
    'https://rickandmortyapi.com/api/episode/46',
    'https://rickandmortyapi.com/api/episode/47',
    'https://rickandmortyapi.com/api/episode/48',
    'https://rickandmortyapi.com/api/episode/49',
    'https://rickandmortyapi.com/api/episode/51'],
   'url': 'https://rickandmortyapi.com/api/character/4',
   'created': '2017-11-04T19:22:43.665Z'},
  {'id': 5,
   'name': 'Jerry Smith',
   'status': 'Alive',
   'species': 'Human',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'location': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/6',
    'https://rickandmortyapi.com/api/episode/7',
    'https://rickandmortyapi.com/api/episode/8',
    'https://rickandmortyapi.com/api/episode/9',
    'https://rickandmortyapi.com/api/episode/10',
    'https://rickandmortyapi.com/api/episode/11',
    'https://rickandmortyapi.com/api/episode/12',
    'https://rickandmortyapi.com/api/episode/13',
    'https://rickandmortyapi.com/api/episode/14',
    'https://rickandmortyapi.com/api/episode/15',
    'https://rickandmortyapi.com/api/episode/16',
    'https://rickandmortyapi.com/api/episode/18',
    'https://rickandmortyapi.com/api/episode/19',
    'https://rickandmortyapi.com/api/episode/20',
    'https://rickandmortyapi.com/api/episode/21',
    'https://rickandmortyapi.com/api/episode/22',
    'https://rickandmortyapi.com/api/episode/23',
    'https://rickandmortyapi.com/api/episode/26',
    'https://rickandmortyapi.com/api/episode/29',
    'https://rickandmortyapi.com/api/episode/30',
    'https://rickandmortyapi.com/api/episode/31',
    'https://rickandmortyapi.com/api/episode/32',
    'https://rickandmortyapi.com/api/episode/33',
    'https://rickandmortyapi.com/api/episode/35',
    'https://rickandmortyapi.com/api/episode/36',
    'https://rickandmortyapi.com/api/episode/38',
    'https://rickandmortyapi.com/api/episode/39',
    'https://rickandmortyapi.com/api/episode/40',
    'https://rickandmortyapi.com/api/episode/41',
    'https://rickandmortyapi.com/api/episode/42',
    'https://rickandmortyapi.com/api/episode/43',
    'https://rickandmortyapi.com/api/episode/44',
    'https://rickandmortyapi.com/api/episode/45',
    'https://rickandmortyapi.com/api/episode/46',
    'https://rickandmortyapi.com/api/episode/47',
    'https://rickandmortyapi.com/api/episode/48',
    'https://rickandmortyapi.com/api/episode/49',
    'https://rickandmortyapi.com/api/episode/50',
    'https://rickandmortyapi.com/api/episode/51'],
   'url': 'https://rickandmortyapi.com/api/character/5',
   'created': '2017-11-04T19:26:56.301Z'},
  {'id': 6,
   'name': 'Abadango Cluster Princess',
   'status': 'Alive',
   'species': 'Alien',
   'type': '',
   'gender': 'Female',
   'origin': {'name': 'Abadango',
    'url': 'https://rickandmortyapi.com/api/location/2'},
   'location': {'name': 'Abadango',
    'url': 'https://rickandmortyapi.com/api/location/2'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/27'],
   'url': 'https://rickandmortyapi.com/api/character/6',
   'created': '2017-11-04T19:50:28.250Z'},
  {'id': 7,
   'name': 'Abradolf Lincler',
   'status': 'unknown',
   'species': 'Human',
   'type': 'Genetic experiment',
   'gender': 'Male',
   'origin': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'location': {'name': 'Testicle Monster Dimension',
    'url': 'https://rickandmortyapi.com/api/location/21'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/10',
    'https://rickandmortyapi.com/api/episode/11'],
   'url': 'https://rickandmortyapi.com/api/character/7',
   'created': '2017-11-04T19:59:20.523Z'},
  {'id': 8,
   'name': 'Adjudicator Rick',
   'status': 'Dead',
   'species': 'Human',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Citadel of Ricks',
    'url': 'https://rickandmortyapi.com/api/location/3'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/28'],
   'url': 'https://rickandmortyapi.com/api/character/8',
   'created': '2017-11-04T20:03:34.737Z'},
  {'id': 9,
   'name': 'Agency Director',
   'status': 'Dead',
   'species': 'Human',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'location': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/24'],
   'url': 'https://rickandmortyapi.com/api/character/9',
   'created': '2017-11-04T20:06:54.976Z'},
  {'id': 10,
   'name': 'Alan Rails',
   'status': 'Dead',
   'species': 'Human',
   'type': 'Superhuman (Ghost trains summoner)',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': "Worldender's lair",
    'url': 'https://rickandmortyapi.com/api/location/4'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/25'],
   'url': 'https://rickandmortyapi.com/api/character/10',
   'created': '2017-11-04T20:19:09.017Z'},
  {'id': 11,
   'name': 'Albert Einstein',
   'status': 'Dead',
   'species': 'Human',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'Earth (C-137)',
    'url': 'https://rickandmortyapi.com/api/location/1'},
   'location': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/11.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/12'],
   'url': 'https://rickandmortyapi.com/api/character/11',
   'created': '2017-11-04T20:20:20.965Z'},
  {'id': 12,
   'name': 'Alexander',
   'status': 'Dead',
   'species': 'Human',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'Earth (C-137)',
    'url': 'https://rickandmortyapi.com/api/location/1'},
   'location': {'name': 'Anatomy Park',
    'url': 'https://rickandmortyapi.com/api/location/5'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/12.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/3'],
   'url': 'https://rickandmortyapi.com/api/character/12',
   'created': '2017-11-04T20:32:33.144Z'},
  {'id': 13,
   'name': 'Alien Googah',
   'status': 'unknown',
   'species': 'Alien',
   'type': '',
   'gender': 'unknown',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/13.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/31'],
   'url': 'https://rickandmortyapi.com/api/character/13',
   'created': '2017-11-04T20:33:30.779Z'},
  {'id': 14,
   'name': 'Alien Morty',
   'status': 'unknown',
   'species': 'Alien',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Citadel of Ricks',
    'url': 'https://rickandmortyapi.com/api/location/3'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/14.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/10'],
   'url': 'https://rickandmortyapi.com/api/character/14',
   'created': '2017-11-04T20:51:31.373Z'},
  {'id': 15,
   'name': 'Alien Rick',
   'status': 'unknown',
   'species': 'Alien',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Citadel of Ricks',
    'url': 'https://rickandmortyapi.com/api/location/3'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/15.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/10'],
   'url': 'https://rickandmortyapi.com/api/character/15',
   'created': '2017-11-04T20:56:13.215Z'},
  {'id': 16,
   'name': 'Amish Cyborg',
   'status': 'Dead',
   'species': 'Alien',
   'type': 'Parasite',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/16.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/15'],
   'url': 'https://rickandmortyapi.com/api/character/16',
   'created': '2017-11-04T21:12:45.235Z'},
  {'id': 17,
   'name': 'Annie',
   'status': 'Alive',
   'species': 'Human',
   'type': '',

In [ ]:
data = r.json()
print(data['info'])

{'count': 826, 'pages': 42, 'next': 'https://rickandmortyapi.com/api/character?page=2', 'prev': None}

In [ ]:
pages = data['info']['pages']

In [ ]:
data['results'][0]

{'id': 1,
 'name': 'Rick Sanchez',
 'status': 'Alive',
 'species': 'Human',
 'type': '',
 'gender': 'Male',
 'origin': {'name': 'Earth (C-137)',
  'url': 'https://rickandmortyapi.com/api/location/1'},
 'location': {'name': 'Citadel of Ricks',
  'url': 'https://rickandmortyapi.com/api/location/3'},
 'image': 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
 'episode': ['https://rickandmortyapi.com/api/episode/1',
  'https://rickandmortyapi.com/api/episode/2',
  'https://rickandmortyapi.com/api/episode/3',
  'https://rickandmortyapi.com/api/episode/4',
  'https://rickandmortyapi.com/api/episode/5',
  'https://rickandmortyapi.com/api/episode/6',
  'https://rickandmortyapi.com/api/episode/7',
  'https://rickandmortyapi.com/api/episode/8',
  'https://rickandmortyapi.com/api/episode/9',
  'https://rickandmortyapi.com/api/episode/10',
  'https://rickandmortyapi.com/api/episode/11',
  'https://rickandmortyapi.com/api/episode/12',
  'https://rickandmortyapi.com/api/episode/13',
  'https://rickandmortyapi.com/api/episode/14',
  'https://rickandmortyapi.com/api/episode/15',
  'https://rickandmortyapi.com/api/episode/16',
  'https://rickandmortyapi.com/api/episode/17',
  'https://rickandmortyapi.com/api/episode/18',
  'https://rickandmortyapi.com/api/episode/19',
  'https://rickandmortyapi.com/api/episode/20',
  'https://rickandmortyapi.com/api/episode/21',
  'https://rickandmortyapi.com/api/episode/22',
  'https://rickandmortyapi.com/api/episode/23',
  'https://rickandmortyapi.com/api/episode/24',
  'https://rickandmortyapi.com/api/episode/25',
  'https://rickandmortyapi.com/api/episode/26',
  'https://rickandmortyapi.com/api/episode/27',
  'https://rickandmortyapi.com/api/episode/28',
  'https://rickandmortyapi.com/api/episode/29',
  'https://rickandmortyapi.com/api/episode/30',
  'https://rickandmortyapi.com/api/episode/31',
  'https://rickandmortyapi.com/api/episode/32',
  'https://rickandmortyapi.com/api/episode/33',
  'https://rickandmortyapi.com/api/episode/34',
  'https://rickandmortyapi.com/api/episode/35',
  'https://rickandmortyapi.com/api/episode/36',
  'https://rickandmortyapi.com/api/episode/37',
  'https://rickandmortyapi.com/api/episode/38',
  'https://rickandmortyapi.com/api/episode/39',
  'https://rickandmortyapi.com/api/episode/40',
  'https://rickandmortyapi.com/api/episode/41',
  'https://rickandmortyapi.com/api/episode/42',
  'https://rickandmortyapi.com/api/episode/43',
  'https://rickandmortyapi.com/api/episode/44',
  'https://rickandmortyapi.com/api/episode/45',
  'https://rickandmortyapi.com/api/episode/46',
  'https://rickandmortyapi.com/api/episode/47',
  'https://rickandmortyapi.com/api/episode/48',
  'https://rickandmortyapi.com/api/episode/49',
  'https://rickandmortyapi.com/api/episode/50',
  'https://rickandmortyapi.com/api/episode/51'],
 'url': 'https://rickandmortyapi.com/api/character/1',
 'created': '2017-11-04T18:48:46.250Z'}

In [ ]:
data['results'][0]['name']

'Rick Sanchez'

In [ ]:
name = data['results'][0]['name']
episodes = data['results'][0]['episode']
episodes

['https://rickandmortyapi.com/api/episode/1',
 'https://rickandmortyapi.com/api/episode/2',
 'https://rickandmortyapi.com/api/episode/3',
 'https://rickandmortyapi.com/api/episode/4',
 'https://rickandmortyapi.com/api/episode/5',
 'https://rickandmortyapi.com/api/episode/6',
 'https://rickandmortyapi.com/api/episode/7',
 'https://rickandmortyapi.com/api/episode/8',
 'https://rickandmortyapi.com/api/episode/9',
 'https://rickandmortyapi.com/api/episode/10',
 'https://rickandmortyapi.com/api/episode/11',
 'https://rickandmortyapi.com/api/episode/12',
 'https://rickandmortyapi.com/api/episode/13',
 'https://rickandmortyapi.com/api/episode/14',
 'https://rickandmortyapi.com/api/episode/15',
 'https://rickandmortyapi.com/api/episode/16',
 'https://rickandmortyapi.com/api/episode/17',
 'https://rickandmortyapi.com/api/episode/18',
 'https://rickandmortyapi.com/api/episode/19',
 'https://rickandmortyapi.com/api/episode/20',
 'https://rickandmortyapi.com/api/episode/21',
 'https://rickandmortyapi.com/api/episode/22',
 'https://rickandmortyapi.com/api/episode/23',
 'https://rickandmortyapi.com/api/episode/24',
 'https://rickandmortyapi.com/api/episode/25',
 'https://rickandmortyapi.com/api/episode/26',
 'https://rickandmortyapi.com/api/episode/27',
 'https://rickandmortyapi.com/api/episode/28',
 'https://rickandmortyapi.com/api/episode/29',
 'https://rickandmortyapi.com/api/episode/30',
 'https://rickandmortyapi.com/api/episode/31',
 'https://rickandmortyapi.com/api/episode/32',
 'https://rickandmortyapi.com/api/episode/33',
 'https://rickandmortyapi.com/api/episode/34',
 'https://rickandmortyapi.com/api/episode/35',
 'https://rickandmortyapi.com/api/episode/36',
 'https://rickandmortyapi.com/api/episode/37',
 'https://rickandmortyapi.com/api/episode/38',
 'https://rickandmortyapi.com/api/episode/39',
 'https://rickandmortyapi.com/api/episode/40',
 'https://rickandmortyapi.com/api/episode/41',
 'https://rickandmortyapi.com/api/episode/42',
 'https://rickandmortyapi.com/api/episode/43',
 'https://rickandmortyapi.com/api/episode/44',
 'https://rickandmortyapi.com/api/episode/45',
 'https://rickandmortyapi.com/api/episode/46',
 'https://rickandmortyapi.com/api/episode/47',
 'https://rickandmortyapi.com/api/episode/48',
 'https://rickandmortyapi.com/api/episode/49',
 'https://rickandmortyapi.com/api/episode/50',
 'https://rickandmortyapi.com/api/episode/51']

In [ ]:
len(episodes)

51

In [16]:
def main_request(baseurl, endpoint):
    r = requests.get(baseurl + endpoint)
    return r.json()

In [17]:
data = main_request(baseurl, endpoint)

In [18]:
def get_pages(response):
    return response['info']['pages']

In [ ]:
get_pages(data)

42

In [ ]:
def parse_json(response):
    for item in response['results']:
        print(item['name'], len(item['episode']))
    return

In [ ]:
parse_json(data)

Rick Sanchez 51
Morty Smith 51
Summer Smith 42
Beth Smith 42
Jerry Smith 39
Abadango Cluster Princess 1
Abradolf Lincler 2
Adjudicator Rick 1
Agency Director 1
Alan Rails 1
Albert Einstein 1
Alexander 1
Alien Googah 1
Alien Morty 1
Alien Rick 1
Amish Cyborg 1
Annie 1
Antenna Morty 2
Antenna Rick 1
Ants in my Eyes Johnson 1

In [ ]:
#new version
def parse_json(response):
    charlist = []
    for item in response['results']:
        char = {
            "name" : item['name'],
            "no_ep": len(item['episode']),
        }
        charlist.append(char)
    return charlist

In [ ]:
parse_json(data)

[{'name': 'Rick Sanchez', 'no_ep': 51},
 {'name': 'Morty Smith', 'no_ep': 51},
 {'name': 'Summer Smith', 'no_ep': 42},
 {'name': 'Beth Smith', 'no_ep': 42},
 {'name': 'Jerry Smith', 'no_ep': 39},
 {'name': 'Abadango Cluster Princess', 'no_ep': 1},
 {'name': 'Abradolf Lincler', 'no_ep': 2},
 {'name': 'Adjudicator Rick', 'no_ep': 1},
 {'name': 'Agency Director', 'no_ep': 1},
 {'name': 'Alan Rails', 'no_ep': 1},
 {'name': 'Albert Einstein', 'no_ep': 1},
 {'name': 'Alexander', 'no_ep': 1},
 {'name': 'Alien Googah', 'no_ep': 1},
 {'name': 'Alien Morty', 'no_ep': 1},
 {'name': 'Alien Rick', 'no_ep': 1},
 {'name': 'Amish Cyborg', 'no_ep': 1},
 {'name': 'Annie', 'no_ep': 1},
 {'name': 'Antenna Morty', 'no_ep': 2},
 {'name': 'Antenna Rick', 'no_ep': 1},
 {'name': 'Ants in my Eyes Johnson', 'no_ep': 1}]

In [ ]:
#updated function
def main_request(baseurl, endpoint, x):
    r = requests.get(baseurl+endpoint+ f'?page={x}')
    return r.json()

In [ ]:
main_request(baseurl, endpoint, 2)

{'info': {'count': 826,
  'pages': 42,
  'next': 'https://rickandmortyapi.com/api/character?page=3',
  'prev': 'https://rickandmortyapi.com/api/character?page=1'},
 'results': [{'id': 21,
   'name': 'Aqua Morty',
   'status': 'unknown',
   'species': 'Humanoid',
   'type': 'Fish-Person',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Citadel of Ricks',
    'url': 'https://rickandmortyapi.com/api/location/3'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/21.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/10',
    'https://rickandmortyapi.com/api/episode/22'],
   'url': 'https://rickandmortyapi.com/api/character/21',
   'created': '2017-11-04T22:39:48.055Z'},
  {'id': 22,
   'name': 'Aqua Rick',
   'status': 'unknown',
   'species': 'Humanoid',
   'type': 'Fish-Person',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Citadel of Ricks',
    'url': 'https://rickandmortyapi.com/api/location/3'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/22.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/10',
    'https://rickandmortyapi.com/api/episode/22',
    'https://rickandmortyapi.com/api/episode/28'],
   'url': 'https://rickandmortyapi.com/api/character/22',
   'created': '2017-11-04T22:41:07.171Z'},
  {'id': 23,
   'name': 'Arcade Alien',
   'status': 'unknown',
   'species': 'Alien',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Immortality Field Resort',
    'url': 'https://rickandmortyapi.com/api/location/7'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/23.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/13',
    'https://rickandmortyapi.com/api/episode/19',
    'https://rickandmortyapi.com/api/episode/21',
    'https://rickandmortyapi.com/api/episode/25',
    'https://rickandmortyapi.com/api/episode/26'],
   'url': 'https://rickandmortyapi.com/api/character/23',
   'created': '2017-11-05T08:43:05.095Z'},
  {'id': 24,
   'name': 'Armagheadon',
   'status': 'Alive',
   'species': 'Alien',
   'type': 'Cromulon',
   'gender': 'Male',
   'origin': {'name': 'Signus 5 Expanse',
    'url': 'https://rickandmortyapi.com/api/location/22'},
   'location': {'name': 'Signus 5 Expanse',
    'url': 'https://rickandmortyapi.com/api/location/22'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/24.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/16'],
   'url': 'https://rickandmortyapi.com/api/character/24',
   'created': '2017-11-05T08:48:30.776Z'},
  {'id': 25,
   'name': 'Armothy',
   'status': 'Dead',
   'species': 'unknown',
   'type': 'Self-aware arm',
   'gender': 'Male',
   'origin': {'name': 'Post-Apocalyptic Earth',
    'url': 'https://rickandmortyapi.com/api/location/8'},
   'location': {'name': 'Post-Apocalyptic Earth',
    'url': 'https://rickandmortyapi.com/api/location/8'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/25.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/23'],
   'url': 'https://rickandmortyapi.com/api/character/25',
   'created': '2017-11-05T08:54:29.343Z'},
  {'id': 26,
   'name': 'Arthricia',
   'status': 'Alive',
   'species': 'Alien',
   'type': 'Cat-Person',
   'gender': 'Female',
   'origin': {'name': 'Purge Planet',
    'url': 'https://rickandmortyapi.com/api/location/9'},
   'location': {'name': 'Purge Planet',
    'url': 'https://rickandmortyapi.com/api/location/9'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/26.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/20'],
   'url': 'https://rickandmortyapi.com/api/character/26',
   'created': '2017-11-05T08:56:46.165Z'},
  {'id': 27,
   'name': 'Artist Morty',
   'status': 'Alive',
   'species': 'Human',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Citadel of Ricks',
    'url': 'https://rickandmortyapi.com/api/location/3'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/27.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/10',
    'https://rickandmortyapi.com/api/episode/28'],
   'url': 'https://rickandmortyapi.com/api/character/27',
   'created': '2017-11-05T08:59:07.457Z'},
  {'id': 28,
   'name': 'Attila Starwar',
   'status': 'Alive',
   'species': 'Human',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Interdimensional Cable',
    'url': 'https://rickandmortyapi.com/api/location/6'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/28.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/8',
    'https://rickandmortyapi.com/api/episode/13',
    'https://rickandmortyapi.com/api/episode/17'],
   'url': 'https://rickandmortyapi.com/api/character/28',
   'created': '2017-11-05T09:02:16.595Z'},
  {'id': 29,
   'name': 'Baby Legs',
   'status': 'Alive',
   'species': 'Human',
   'type': 'Human with baby legs',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Interdimensional Cable',
    'url': 'https://rickandmortyapi.com/api/location/6'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/29.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/8'],
   'url': 'https://rickandmortyapi.com/api/character/29',
   'created': '2017-11-05T09:06:19.644Z'},
  {'id': 30,
   'name': 'Baby Poopybutthole',
   'status': 'Alive',
   'species': 'Poopybutthole',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'unknown', 'url': ''},
   'image': 'https://rickandmortyapi.com/api/character/avatar/30.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/31'],
   'url': 'https://rickandmortyapi.com/api/character/30',
   'created': '2017-11-05T09:13:16.483Z'},
  {'id': 31,
   'name': 'Baby Wizard',
   'status': 'Dead',
   'species': 'Alien',
   'type': 'Parasite',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/31.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/15'],
   'url': 'https://rickandmortyapi.com/api/character/31',
   'created': '2017-11-05T09:15:11.286Z'},
  {'id': 32,
   'name': 'Bearded Lady',
   'status': 'Dead',
   'species': 'Alien',
   'type': 'Parasite',
   'gender': 'Female',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Earth (Replacement Dimension)',
    'url': 'https://rickandmortyapi.com/api/location/20'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/32.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/15'],
   'url': 'https://rickandmortyapi.com/api/character/32',
   'created': '2017-11-05T09:18:04.184Z'},
  {'id': 33,
   'name': 'Beebo',
   'status': 'Dead',
   'species': 'Alien',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'Venzenulon 7',
    'url': 'https://rickandmortyapi.com/api/location/10'},
   'location': {'name': 'Venzenulon 7',
    'url': 'https://rickandmortyapi.com/api/location/10'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/33.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/29'],
   'url': 'https://rickandmortyapi.com/api/character/33',
   'created': '2017-11-05T09:21:55.595Z'},
  {'id': 34,
   'name': 'Benjamin',
   'status': 'Alive',
   'species': 'Poopybutthole',
   'type': '',
   'gender': 'Male',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'Interdimensional Cable',
    'url': 'https://rickandmortyapi.com/api/location/6'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/34.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/8',
    'https://rickandmortyapi.com/api/episode/13',
    'https://rickandmortyapi.com/api/episode/17'],
   'url': 'https://rickandmortyapi.com/api/character/34',
   'created': '2017-11-05T09:24:04.748Z'},
  {'id': 35,
   'name': 'Bepisian',
   'status': 'Alive',
   'species': 'Alien',
   'type': 'Bepisian',
   'gender': 'unknown',
   'origin': {'name': 'Bepis 9',
    'url': 'https://rickandmortyapi.com/api/location/11'},
   'location': {'name': 'Bepis 9',
    'url': 'https://rickandmortyapi.com/api/location/11'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/35.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/1',
    'https://rickandmortyapi.com/api/episode/11',
    'https://rickandmortyapi.com/api/episode/19',
    'https://rickandmortyapi.com/api/episode/25'],
   'url': 'https://rickandmortyapi.com/api/character/35',
   'created': '2017-11-05T09:27:38.491Z'},
  {'id': 36,
   'name': 'Beta-Seven',
   'status': 'Alive',
   'species': 'Alien',
   'type': 'Hivemind',
   'gender': 'unknown',
   'origin': {'name': 'unknown', 'url': ''},
   'location': {'name': 'unknown', 'url': ''},
   'image': 'https://rickandmortyapi.com/api/character/avatar/36.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/14'],
   'url': 'https://rickandmortyapi.com/api/character/36',
   'created': '2017-11-05T09:31:08.952Z'},
  {'id': 37,
   'name': 'Beth Sanchez',
   'status': 'Alive',
   'species': 'Human',
   'type': '',
   'gender': 'Female',
   'origin': {'name': 'Earth (C-500A)',
    'url': 'https://rickandmortyapi.com/api/location/23'},
   'location': {'name': 'Earth (C-500A)',
    'url': 'https://rickandmortyapi.com/api/location/23'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/37.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/8'],
   'url': 'https://rickandmortyapi.com/api/character/37',
   'created': '2017-11-05T09:38:22.960Z'},
  {'id': 38,
   'name': 'Beth Smith',
   'status': 'Alive',
   'species': 'Human',
   'type': '',
   'gender': 'Female',
   'origin': {'name': 'Earth (C-137)',
    'url': 'https://rickandmortyapi.com/api/location/1'},
   'location': {'name': 'Earth (C-137)',
    'url': 'https://rickandmortyapi.com/api/location/1'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/38.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/1',
    'https://rickandmortyapi.com/api/episode/2',
    'https://rickandmortyapi.com/api/episode/3',
    'https://rickandmortyapi.com/api/episode/4',
    'https://rickandmortyapi.com/api/episode/5',
    'https://rickandmortyapi.com/api/episode/6',
    'https://rickandmortyapi.com/api/episode/22',
    'https://rickandmortyapi.com/api/episode/51'],
   'url': 'https://rickandmortyapi.com/api/character/38',
   'created': '2017-11-05T09:48:44.230Z'},
  {'id': 39,
   'name': 'Beth Smith',
   'status': 'Alive',
   'species': 'Human',
   'type': '',
   'gender': 'Female',
   'origin': {'name': "Earth (Evil Rick's Target Dimension)",
    'url': 'https://rickandmortyapi.com/api/location/34'},
   'location': {'name': "Earth (Evil Rick's Target Dimension)",
    'url': 'https://rickandmortyapi.com/api/location/34'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/39.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/10'],
   'url': 'https://rickandmortyapi.com/api/character/39',
   'created': '2017-11-05T09:52:31.777Z'},
  {'id': 40,
   'name': "Beth's Mytholog",
   'status': 'Dead',
   'species': 'Mythological Creature',
   'type': 'Mytholog',
   'gender': 'Female',
   'origin': {'name': 'Nuptia 4',
    'url': 'https://rickandmortyapi.com/api/location/13'},
   'location': {'name': 'Nuptia 4',
    'url': 'https://rickandmortyapi.com/api/location/13'},
   'image': 'https://rickandmortyapi.com/api/character/avatar/40.jpeg',
   'episode': ['https://rickandmortyapi.com/api/episode/18'],
   'url': 'https://rickandmortyapi.com/api/character/40',
   'created': '2017-11-05T10:02:26.701Z'}]}

In [ ]:
mainlist = []
data = main_request(baseurl, endpoint, 1)
for x in range(1, get_pages(data)+1):
    mainlist.extend(parse_json(main_request(baseurl, endpoint, x)))

In [ ]:
print(len(mainlist))

826

In [ ]:
df = pd.DataFrame(mainlist)

In [ ]:
df.head()

           name  no_ep
0  Rick Sanchez     51
1   Morty Smith     51
2  Summer Smith     42
3    Beth Smith     42
4   Jerry Smith     39

In [ ]:
df.tail()

             name  no_ep
821   Young Jerry      1
822    Young Beth      1
823    Young Beth      1
824   Young Jerry      1
825  Butter Robot      1

In [ ]:
#add in the id to the function
def parse_json(response):
    charlist = []
    for item in response['results']:
        char = {
            "id": item['id'],
            "name" : item['name'],
            "no_ep": len(item['episode']),
        }
        charlist.append(char)
    return charlist

In [ ]:
mainlist = []
data = main_request(baseurl, endpoint, 1)
for x in range(1, get_pages(data)+1):
    mainlist.extend(parse_json(main_request(baseurl, endpoint, x)))

In [ ]:
df = pd.DataFrame(mainlist)
df.to_csv('charlists.csv', index=False)

In [ ]:
df.head()

   id          name  no_ep
0   1  Rick Sanchez     51
1   2   Morty Smith     51
2   3  Summer Smith     42
3   4    Beth Smith     42
4   5   Jerry Smith     39

In [ ]:
df.tail()

      id          name  no_ep
821  822   Young Jerry      1
822  823    Young Beth      1
823  824    Young Beth      1
824  825   Young Jerry      1
825  826  Butter Robot      1