In [16]:
import pandas as pd 
import numpy as np

In [ ]:
# Drop a column
df = df.drop('column_name', axis=1)

# Drop multiple columns
df = df.drop(['col1', 'col2'], axis=1)

# Drop a row by index
df = df.drop(0)

# Drop rows with missing values
df = df.dropna()

axis=0 means rows
axis=1 means columns
By default, .drop() returns a new DataFrame unless you use inplace=True.

In [ ]:
# Drop a single column
df = df.drop('Unnamed: 0', axis=1)

# Drop multiple columns
df = df.drop(['email', 'phone'], axis=1)

# Drop a row by index (e.g., row 5)
df = df.drop(5, axis=0)

# Drop rows 0 through 3
df = df.drop([0, 1, 2, 3], axis=0)

You can also drop in place, which means that the DataFrame is modified without having to save it by typing in 'df =' first:

df.drop('Unnamed: 0', axis=1, inplace=True)

Potiental Mistakes:

Forgetting axis=1 when dropping columns (the default is axis=0, so it tries to drop a row instead)
Not assigning the result back to df (unless using inplace=True)
Dropping rows by label when your index isn't numeric (consider using .reset_index() first if needed)

In [4]:
# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['NYC', 'LA', 'Chicago', 'Miami'],
    'Email': ['a@example.com', 'b@example.com', 'c@example.com', 'd@example.com']
}

df = pd.DataFrame(data)

df

      Name  Age     City          Email
0    Alice   25      NYC  a@example.com
1      Bob   30       LA  b@example.com
2  Charlie   35  Chicago  c@example.com
3    David   40    Miami  d@example.com

In [5]:
# 1. Drop the Email column and store in new variable
df_no_email = df.drop(columns=['Email'])
print(df_no_email)

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40    Miami

In [6]:
# 2. Drop row with index 2 in place
df.drop(index=2, inplace=True)
print(df)

    Name  Age   City          Email
0  Alice   25    NYC  a@example.com
1    Bob   30     LA  b@example.com
3  David   40  Miami  d@example.com

In [8]:
# Re-create DataFrame for next steps- just leave this alone
df = pd.DataFrame(data)
df

      Name  Age     City          Email
0    Alice   25      NYC  a@example.com
1      Bob   30       LA  b@example.com
2  Charlie   35  Chicago  c@example.com
3    David   40    Miami  d@example.com

In [9]:
# 3. Drop City and Email columns, assign back to df
df = df.drop(columns=['Email', 'City'])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [11]:
# Re-create again for next step
df = pd.DataFrame(data)
df

      Name  Age     City          Email
0    Alice   25      NYC  a@example.com
1      Bob   30       LA  b@example.com
2  Charlie   35  Chicago  c@example.com
3    David   40    Miami  d@example.com

In [13]:
# 4. Drop first and last row, store in df_trimmed
df_trimmed = df.drop(index=[0,3])
print(df_trimmed)

      Name  Age     City          Email
1      Bob   30       LA  b@example.com
2  Charlie   35  Chicago  c@example.com

Replacing Values:

Sometimes, the data you're working with has placeholder or incorrect values — like "N/A", "?", "none", or "missing" instead of actual nulls (NaN). Other times, values are simply mislabeled or need to be standardized (e.g., "yes" and "Yes" should be treated the same).

The .replace() method in Pandas is a quick and flexible way to update those values.

In [ ]:
df['column_name'].replace(to_replace, value)

In [ ]:
df['Gender'].replace('M', 'Male') # Replaces a single value
df['Gender'].replace({'M': 'Male', 'F': 'Female'}) # Replaces multiple values
df.replace('?', np.nan) # Replaces all ? in the DataFrame with NaN

Pro tip: Replacing is often a first step before handling missing values — for example, converting "N/A" or -1 into np.nan so you can later drop or fill those values cleanly.

In [ ]:
#Handling Missing Values
df.isnull() # Returns a DataFrame of True/False values showing where data is missing
df.isnull().sum() # This will tell you how many missing values are in each column.

In the real world, data is rarely perfect. It's common to have missing or incomplete values in your dataset. These could be empty cells in a spreadsheet, null entries in a database, or NaN (Not a Number) values in a DataFrame.

Missing values matter because they can break your analysis or skew results — especially if they exist in important columns you're trying to calculate things on.

In [ ]:
df.dropna() 

#By default, drops any row with at least one missing value. 
#If you want to drop an entire column with any missing values, set axis = 1:

df.dropna(axis=1)

df.fillna(0)                      # Replace missing values with 0
df.fillna('Unknown')             # Replace missing strings with a placeholder
df.fillna(df['Age'].mean())      # Replace with the column mean (or median, or mode)

Best Practices:


There’s no one-size-fits-all answer - your approach depends on how much is missing and what kind of analysis you're doing. But here are some helpful guidelines:

-Drop the column if it's mostly missing and not essential
-Drop the row if it’s just a few and you have enough data
-Fill in the value if it’s just missing a little and you can justify what to use

Common fill strategies:
*Use the mean or median for numbers
*Use the most common value for categories
*Use "Unknown" or "Not Provided" for missing strings
*Use 0 or a flag like False for missing booleans

In [17]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, np.nan, 35, 40, None],
    'City': ['NYC', 'LA', None, 'Miami', 'Boston']
}
df = pd.DataFrame(data)
df

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0    None
3    David  40.0   Miami
4      Eva   NaN  Boston

In [18]:
# 1. View the DataFrame
print(df)

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0    None
3    David  40.0   Miami
4      Eva   NaN  Boston

In [20]:
# 2. Show where values are missing
print(df.isnull())

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [21]:
# 3. Count of missing values by column
print(df.isnull().sum())

Name    0
Age     2
City    1
dtype: int64

In [24]:
# 4. Drop rows with missing data
print(df.dropna())

    Name   Age   City
0  Alice  25.0    NYC
3  David  40.0  Miami

In [25]:
# 5. Re-create original - leave this part alone
df = pd.DataFrame(data)

In [26]:
# 6. Drop columns with missing data
print(df.dropna(axis=1))

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eva

In [27]:
# 7. Re-create again - Leave this alone again
df = pd.DataFrame(data)

In [29]:
# 8. Fill missing Age with mean
df['Age'] = df['Age'].fillna(df['Age'].mean()) 
print(df)

      Name        Age    City
0    Alice  25.000000     NYC
1      Bob  33.333333      LA
2  Charlie  35.000000    None
3    David  40.000000   Miami
4      Eva  33.333333  Boston

In [33]:
# 9. Fill missing City with "Unknown"
df['City'] = df['City'].fillna('Unknown')
print(df)

      Name        Age     City
0    Alice  25.000000      NYC
1      Bob  33.333333       LA
2  Charlie  35.000000  Unknown
3    David  40.000000    Miami
4      Eva  33.333333   Boston

Fixing Data Types:

In [ ]:
df.dtypes #To view the current data types of your columns
df.info()

#Why Data Types Matter

#Data types affect what you can do with each column. For example:

#You can’t calculate a mean on a column of strings, even if they look like numbers.
#You can’t filter by date unless pandas knows it’s a datetime object.
#You might waste memory or processing time using a float64 column that only holds integers from 1–5

In [ ]:
df['ColumnName'] = df['ColumnName'].astype(new_type)
#To change a column’s data type

#EXAMPLES:

# Convert numeric strings to actual numbers
df['Revenue'] = df['Revenue'].astype(float)

# Convert integers to strings (e.g., zip codes)
df['ZipCode'] = df['ZipCode'].astype(str)

# Convert float to integer (use with caution)
df['Quantity'] = df['Quantity'].astype(int)

#note:Converting from float to int will drop decimal values (not round!), 
#so make sure that makes sense for your context.

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
#To convert a column to datetime format (so you can do time-based filtering or aggregation)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y')
#Pandas is smart about most common date formats, but if it doesn’t work automatically, 
#you can provide a format string like this:

In [ ]:
.duplicated()
#returns a Boolean Series indicating if a row is a duplicate of a previous one

.drop_duplicates()
#returns a new DataFrame with duplicates removed

In [34]:
# Sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob'],
    'Age': [25, 30, 35, 25, 30]
}

df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    Alice   25
4      Bob   30

In [ ]:
# Check which rows are duplicates (compares to earlier rows)
df.duplicated()

# Drop duplicates (keeps first occurrence by default)
df_cleaned = df.drop_duplicates()

Optional Arguments for drop_duplicates():

*keep='first' (default): keeps the first occurrence, drops the rest
*keep='last': keeps the last occurrence
*keep=False: drops all duplicates

In [ ]:
# Only consider 'Name' column when looking for duplicates
df.drop_duplicates(subset='Name')

In [35]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob', 'Diana'],
    'Age': [25, 30, 35, 25, 30, 40],
    'City': ['NYC', 'LA', 'SF', 'NYC', 'LA', 'NYC']
}

df = pd.DataFrame(data)
df

      Name  Age City
0    Alice   25  NYC
1      Bob   30   LA
2  Charlie   35   SF
3    Alice   25  NYC
4      Bob   30   LA
5    Diana   40  NYC

In [36]:
# 1. Find which rows are duplicates (across all columns)
print("\nDuplicated rows (True if row is a duplicate of an earlier one):")
print(df.duplicated())

Duplicated rows (True if row is a duplicate of an earlier one):
0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [38]:
# 2. Drop duplicate rows (keeping the first occurrence)
print("\nDataFrame with duplicates dropped (keep='first'):")
print(df.drop_duplicates())

DataFrame with duplicates dropped (keep='first'):
      Name  Age City
0    Alice   25  NYC
1      Bob   30   LA
2  Charlie   35   SF
5    Diana   40  NYC

In [39]:
# 3. Drop duplicate rows (keeping only the last occurrence)
print("\nDataFrame with duplicates dropped (keep='last'):")
print(df.drop_duplicates(keep='last'))

DataFrame with duplicates dropped (keep='last'):
      Name  Age City
2  Charlie   35   SF
3    Alice   25  NYC
4      Bob   30   LA
5    Diana   40  NYC

In [40]:
# 4. Drop ALL duplicates (remove both original and duplicate)
print("\nDataFrame with ALL duplicates removed (keep=False):")
print(df.drop_duplicates(keep=False))

DataFrame with ALL duplicates removed (keep=False):
      Name  Age City
2  Charlie   35   SF
5    Diana   40  NYC