In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
#normal Groupby
df.groupby('time')['total_bill'].mean()

C:\Users\tm96\AppData\Local\Temp\ipykernel_15956\4283297709.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].mean()

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [5]:
#.to_frame
df.groupby('time')['total_bill'].mean().to_frame('avg_bill')

C:\Users\tm96\AppData\Local\Temp\ipykernel_15956\3325110290.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].mean().to_frame('avg_bill')

         avg_bill
time
Lunch   17.168676
Dinner  20.797159

In [ ]:
#.reset_index() - adds the index bar back
df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index()

C:\Users\tm96\AppData\Local\Temp\ipykernel_15956\3177919205.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index()

     time   avg_bill
0   Lunch  17.168676
1  Dinner  20.797159

In [9]:
#.sort_values()
df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill', ascending=False)

C:\Users\tm96\AppData\Local\Temp\ipykernel_15956\3635873870.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill', ascending=False)

     time   avg_bill
1  Dinner  20.797159
0   Lunch  17.168676

In [10]:
#assign to new dataframe
avgbill = df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill', ascending=False)

C:\Users\tm96\AppData\Local\Temp\ipykernel_15956\2773018187.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avgbill = df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill', ascending=False)

In [11]:
avgbill.head()

     time   avg_bill
1  Dinner  20.797159
0   Lunch  17.168676

In [ ]:
#common calculations .sum() / .count() / .min() / .Max() / .mean() 
df.groupby('time')['total_bill'].count()
#.count does NOT count nulls

C:\Users\tm96\AppData\Local\Temp\ipykernel_15956\1330684491.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].count()

time
Lunch      68
Dinner    176
Name: total_bill, dtype: int64

In [ ]:
df.groupby('time')['total_bill'].size()
#.size counts nulls

C:\Users\tm96\AppData\Local\Temp\ipykernel_15956\3634247635.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].size()

time
Lunch      68
Dinner    176
Name: total_bill, dtype: int64

In [ ]:
df.groupby('time')['total_bill'].nunique()
#nunique will only pull unique items, does not include duplicates

C:\Users\tm96\AppData\Local\Temp\ipykernel_15956\1444668881.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].nunique()

time
Lunch      64
Dinner    168
Name: total_bill, dtype: int64

In [16]:
df.groupby('time')['total_bill'].min()

C:\Users\tm96\AppData\Local\Temp\ipykernel_15956\2885977980.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].min()

time
Lunch     7.51
Dinner    3.07
Name: total_bill, dtype: float64

In [17]:
df.groupby('time')['total_bill'].max()

C:\Users\tm96\AppData\Local\Temp\ipykernel_15956\2011320423.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].max()

time
Lunch     43.11
Dinner    50.81
Name: total_bill, dtype: float64

In [18]:
df.groupby('time')['total_bill'].sum()

C:\Users\tm96\AppData\Local\Temp\ipykernel_15956\3868659607.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].sum()

time
Lunch     1167.47
Dinner    3660.30
Name: total_bill, dtype: float64