In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

In [4]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [5]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
#normal Groupby
df.groupby('time')['total_bill'].mean()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\4283297709.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].mean()

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [7]:
#.to_frame
df.groupby('time')['total_bill'].mean().to_frame('avg_bill')

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\3325110290.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].mean().to_frame('avg_bill')

         avg_bill
time
Lunch   17.168676
Dinner  20.797159

In [8]:
#.reset_index() - adds the index bar back
df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\2028037782.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index()

     time   avg_bill
0   Lunch  17.168676
1  Dinner  20.797159

In [9]:
#.sort_values()
df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill', ascending=False)

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\3635873870.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill', ascending=False)

     time   avg_bill
1  Dinner  20.797159
0   Lunch  17.168676

In [10]:
#assign to new dataframe
avgbill = df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill', ascending=False)

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\2773018187.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avgbill = df.groupby('time')['total_bill'].mean().to_frame('avg_bill').reset_index().sort_values('avg_bill', ascending=False)

In [11]:
avgbill.head()

     time   avg_bill
1  Dinner  20.797159
0   Lunch  17.168676

In [12]:
#common calculations .sum() / .count() / .min() / .Max() / .mean() 
df.groupby('time')['total_bill'].count()
#.count does NOT count nulls

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\844640497.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].count()

time
Lunch      68
Dinner    176
Name: total_bill, dtype: int64

In [13]:
df.groupby('time')['total_bill'].size()
#.size counts nulls

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\2032327456.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].size()

time
Lunch      68
Dinner    176
Name: total_bill, dtype: int64

In [14]:
df.groupby('time')['total_bill'].nunique()
#nunique will only pull unique items, does not include duplicates

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\2366894580.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].nunique()

time
Lunch      64
Dinner    168
Name: total_bill, dtype: int64

In [15]:
df.groupby('time')['total_bill'].min()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\2885977980.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].min()

time
Lunch     7.51
Dinner    3.07
Name: total_bill, dtype: float64

In [16]:
df.groupby('time')['total_bill'].max()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\2011320423.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].max()

time
Lunch     43.11
Dinner    50.81
Name: total_bill, dtype: float64

In [17]:
df.groupby('time')['total_bill'].sum()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\3868659607.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].sum()

time
Lunch     1167.47
Dinner    3660.30
Name: total_bill, dtype: float64

In [18]:
df.groupby('time')['total_bill'].median()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\4105816220.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].median()

time
Lunch     15.965
Dinner    18.390
Name: total_bill, dtype: float64

In [19]:
#Question 1# Find the AVG Tip fpr each night of the week.
df.groupby('day')['tip'].mean()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1857961021.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')['tip'].mean()

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [20]:
#Question 2# Find the Max tip for each sex

df.groupby('time')['total_bill'].max()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1235332834.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].max()

time
Lunch     43.11
Dinner    50.81
Name: total_bill, dtype: float64

In [21]:
#Question 3# ->Quantile --> Top 10 % of Tips each Night
df.groupby('day')['tip'].quantile(.9)

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1662003115.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')['tip'].quantile(.9)

day
Thur    4.920
Fri     4.060
Sat     4.802
Sun     5.035
Name: tip, dtype: float64

In [22]:
#multiple caculations .agg() + formats

df.groupby('time')['total_bill'].agg(['min', 'max'])

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1624024408.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].agg(['min', 'max'])

         min    max
time
Lunch   7.51  43.11
Dinner  3.07  50.81

In [23]:
df.groupby('time')['total_bill'].agg([min, max])

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1458761134.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].agg([min, max])
C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1458761134.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('time')['total_bill'].agg([min, max])
C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1458761134.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('time')['total_bill'].agg([min, max])

         min    max
time
Lunch   7.51  43.11
Dinner  3.07  50.81

In [24]:
df.groupby('time')['total_bill'].agg(['min', np.median, 'max'])

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\2427167228.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].agg(['min', np.median, 'max'])
C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\2427167228.py:1: FutureWarning: The provided callable <function median at 0x000002653670EB60> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('time')['total_bill'].agg(['min', np.median, 'max'])

         min  median    max
time
Lunch   7.51  15.965  43.11
Dinner  3.07  18.390  50.81

In [25]:
df.groupby('time')['total_bill'].agg(minimum ='min', median = np.median, maximum = 'max')

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\2170938858.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].agg(minimum ='min', median = np.median, maximum = 'max')
C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\2170938858.py:1: FutureWarning: The provided callable <function median at 0x000002653670EB60> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('time')['total_bill'].agg(minimum ='min', median = np.median, maximum = 'max')

        minimum  median  maximum
time
Lunch      7.51  15.965    43.11
Dinner     3.07  18.390    50.81

In [26]:
df.groupby('time')['total_bill'].agg(['min', np.median, 'max']).rename(columns = {'min': 'minimum', 'max': 'max'})

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1318102440.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].agg(['min', np.median, 'max']).rename(columns = {'min': 'minimum', 'max': 'max'})
C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1318102440.py:1: FutureWarning: The provided callable <function median at 0x000002653670EB60> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('time')['total_bill'].agg(['min', np.median, 'max']).rename(columns = {'min': 'minimum', 'max': 'max'})

        minimum  median    max
time
Lunch      7.51  15.965  43.11
Dinner     3.07  18.390  50.81

In [27]:
df.groupby('time')['total_bill'].describe()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1293134793.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')['total_bill'].describe()

        count       mean       std   min      25%     50%      75%    max
time
Lunch    68.0  17.168676  7.713882  7.51  12.2350  15.965  19.5325  43.11
Dinner  176.0  20.797159  9.142029  3.07  14.4375  18.390  25.2825  50.81

In [28]:
df.groupby('time')[['tip','total_bill']].mean()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1774718145.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')[['tip','total_bill']].mean()

             tip  total_bill
time
Lunch   2.728088   17.168676
Dinner  3.102670   20.797159

In [29]:
df.groupby(['time', 'day'])[['tip','total_bill']].mean()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\440429959.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['time', 'day'])[['tip','total_bill']].mean()

                  tip  total_bill
time   day
Lunch  Thur  2.767705   17.664754
       Fri   2.382857   12.845714
       Sat        NaN         NaN
       Sun        NaN         NaN
Dinner Thur  3.000000   18.780000
       Fri   2.940000   19.663333
       Sat   2.993103   20.441379
       Sun   3.255132   21.410000

In [30]:
df.groupby(['day', 'time'])[['tip','total_bill']].mean()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\2138650159.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['day', 'time'])[['tip','total_bill']].mean()

                  tip  total_bill
day  time
Thur Lunch   2.767705   17.664754
     Dinner  3.000000   18.780000
Fri  Lunch   2.382857   12.845714
     Dinner  2.940000   19.663333
Sat  Lunch        NaN         NaN
     Dinner  2.993103   20.441379
Sun  Lunch        NaN         NaN
     Dinner  3.255132   21.410000

In [31]:
df.groupby('time')[['tip','total_bill']].mean()
df.groupby(['day', 'time'])[['tip','total_bill']].mean()

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1213099910.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')[['tip','total_bill']].mean()
C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\1213099910.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['day', 'time'])[['tip','total_bill']].mean()

                  tip  total_bill
day  time
Thur Lunch   2.767705   17.664754
     Dinner  3.000000   18.780000
Fri  Lunch   2.382857   12.845714
     Dinner  2.940000   19.663333
Sat  Lunch        NaN         NaN
     Dinner  2.993103   20.441379
Sun  Lunch        NaN         NaN
     Dinner  3.255132   21.410000

In [32]:
#stopped at 23:06 at the youtube video

In [33]:
df.groupby('time')[['tip','total_bill']].mean().reset_index

C:\Users\tm96\AppData\Local\Temp\ipykernel_38092\405774982.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('time')[['tip','total_bill']].mean().reset_index

<bound method DataFrame.reset_index of              tip  total_bill
time
Lunch   2.728088   17.168676
Dinner  3.102670   20.797159>