In [7]:
import pandas as pd
import numpy as np

In [8]:
#renaming using .rename()
df.rename(columns={'old_column': 'new_column'}, inplace=True)

#renaming multiple columns:
df.rename(columns={
    'fname': 'FirstName',
    'lname': 'LastName'
}, inplace=True)

#renaming all columns in one line of code:
df.columns = ['Col1', 'Col2', 'Col3']

Sometimes column names are unclear, inconsistent, or just too long. Renaming them makes your code easier to write and your results easier to interpret — especially when sharing your notebook with others.

For example:

"first_name" → "FirstName" for consistency
"Unnamed: 0" → removed or renamed
"ctry" → "Country" for clarity

In [11]:
data = {
    'fname': ['Alice', 'Bob', 'Charlie'],
    'lname': ['Smith', 'Jones', 'Brown'],
    'ctry': ['USA', 'Canada', 'UK']
}

df = pd.DataFrame(data)

df

     fname  lname    ctry
0    Alice  Smith     USA
1      Bob  Jones  Canada
2  Charlie  Brown      UK

In [13]:
df.rename(columns={
    'fname': 'FirstName',
    'lname': 'LastName'
}, inplace=True)

print("1. Renamed 'fanme' and 'lname': ")
df

1. Renamed 'fanme' and 'lname':

  FirstName LastName    ctry
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

In [19]:
df.columns = ['FirstName', 'LastName',  'Country']
print("\n2. All column names changed:")
df

2. All column names changed:

  FirstName LastName Country
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

In [ ]:
df.sort_values(by='column_name')
#By default, this sorts in ascending order. 

df.sort_values(by='column_name', ascending=False)
#adding ascending=False to have it sort by descending order.

Sometimes you want to sort by more than one column — for example, by Country and then by Score. The following code sorts alphabetically by Country first, and then (within each Country) by Score from highest to lowest:

In [ ]:
df.sort_values(by=['Country', 'Score'], ascending=[True, False])

To sort by the index instead of the values in a column:

In [ ]:
df.sort_index()
# Or reverse for descending order:
df.sort_index(ascending = False)

In [ ]:
.sort_values()
# returns a new DataFrame unless you use inplace=True
#Sorting doesn’t change the original index — the row labels stay the same unless you reset them
#Always check whether sorting logically helps the next steps of your analysis

As you clean and prepare your dataset, you'll often need to rename confusing column names or reorder them for better readability or consistency. This is especially important when you're getting ready to share your dataset with others or use it in reports and visualizations.

You can rename a single column, or multiple columns at once (using a dictionary):

In [ ]:
df.rename(columns={'old_name': 'new_name'}, inplace=True)
df.rename(columns={
    'Dept': 'Department',
    'Sal': 'Salary'
}, inplace=True)

To change the column order, you can directly type in a new list of names for the columns, or dynamically using indexing:

In [ ]:
df = df[['Salary', 'Name', 'Department']]
cols = df.columns.tolist()
new_order = [cols[-1]] + cols[:-1]  # Moves the last column to the front
df = df[new_order]

In [20]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Dept': ['HR', 'Finance', 'IT'],
    'Sal': [60000, 70000, 80000]
}
df = pd.DataFrame(data)
df

      Name     Dept    Sal
0    Alice       HR  60000
1      Bob  Finance  70000
2  Charlie       IT  80000

In [22]:
# 1. Rename 'Dept' to 'Department'and 'Sal' to 'Salary'
df.rename(columns={'old_name': 'new_name'}, inplace=True)
df.rename(columns={
    'Dept': 'Department',
    'Sal': 'Salary'
}, inplace=True)
df

      Name Department  Salary
0    Alice         HR   60000
1      Bob    Finance   70000
2  Charlie         IT   80000

In [24]:
# 2. Reorder columns so 'Salary' appears first, followed by 'Name' and 'Department'
df = df[['Salary', 'Name', 'Department']]
cols = df.columns.tolist()
df

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

In [25]:
# 4. Print the updated DataFrame
df

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT