In [12]:
import pandas as pd
import numpy as np

In [8]:
#renaming using .rename()
df.rename(columns={'old_column': 'new_column'}, inplace=True)

#renaming multiple columns:
df.rename(columns={
    'fname': 'FirstName',
    'lname': 'LastName'
}, inplace=True)

#renaming all columns in one line of code:
df.columns = ['Col1', 'Col2', 'Col3']

Sometimes column names are unclear, inconsistent, or just too long. Renaming them makes your code easier to write and your results easier to interpret — especially when sharing your notebook with others.

For example:

"first_name" → "FirstName" for consistency
"Unnamed: 0" → removed or renamed
"ctry" → "Country" for clarity

In [11]:
data = {
    'fname': ['Alice', 'Bob', 'Charlie'],
    'lname': ['Smith', 'Jones', 'Brown'],
    'ctry': ['USA', 'Canada', 'UK']
}

df = pd.DataFrame(data)

df

     fname  lname    ctry
0    Alice  Smith     USA
1      Bob  Jones  Canada
2  Charlie  Brown      UK

In [13]:
df.rename(columns={
    'fname': 'FirstName',
    'lname': 'LastName'
}, inplace=True)

print("1. Renamed 'fanme' and 'lname': ")
df

1. Renamed 'fanme' and 'lname':

  FirstName LastName    ctry
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

In [19]:
df.columns = ['FirstName', 'LastName',  'Country']
print("\n2. All column names changed:")
df

2. All column names changed:

  FirstName LastName Country
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

In [ ]:
df.sort_values(by='column_name')
#By default, this sorts in ascending order. 

df.sort_values(by='column_name', ascending=False)
#adding ascending=False to have it sort by descending order.

Sometimes you want to sort by more than one column — for example, by Country and then by Score. The following code sorts alphabetically by Country first, and then (within each Country) by Score from highest to lowest:

In [ ]:
df.sort_values(by=['Country', 'Score'], ascending=[True, False])

To sort by the index instead of the values in a column:

In [ ]:
df.sort_index()
# Or reverse for descending order:
df.sort_index(ascending = False)

In [ ]:
.sort_values()
# returns a new DataFrame unless you use inplace=True
#Sorting doesn’t change the original index — the row labels stay the same unless you reset them
#Always check whether sorting logically helps the next steps of your analysis

As you clean and prepare your dataset, you'll often need to rename confusing column names or reorder them for better readability or consistency. This is especially important when you're getting ready to share your dataset with others or use it in reports and visualizations.

You can rename a single column, or multiple columns at once (using a dictionary):

In [ ]:
df.rename(columns={'old_name': 'new_name'}, inplace=True)
df.rename(columns={
    'Dept': 'Department',
    'Sal': 'Salary'
}, inplace=True)

To change the column order, you can directly type in a new list of names for the columns, or dynamically using indexing:

In [ ]:
df = df[['Salary', 'Name', 'Department']]
cols = df.columns.tolist()
new_order = [cols[-1]] + cols[:-1]  # Moves the last column to the front
df = df[new_order]

In [20]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Dept': ['HR', 'Finance', 'IT'],
    'Sal': [60000, 70000, 80000]
}
df = pd.DataFrame(data)
df

      Name     Dept    Sal
0    Alice       HR  60000
1      Bob  Finance  70000
2  Charlie       IT  80000

In [22]:
# 1. Rename 'Dept' to 'Department'and 'Sal' to 'Salary'
df.rename(columns={'old_name': 'new_name'}, inplace=True)
df.rename(columns={
    'Dept': 'Department',
    'Sal': 'Salary'
}, inplace=True)
df

      Name Department  Salary
0    Alice         HR   60000
1      Bob    Finance   70000
2  Charlie         IT   80000

In [24]:
# 2. Reorder columns so 'Salary' appears first, followed by 'Name' and 'Department'
df = df[['Salary', 'Name', 'Department']]
cols = df.columns.tolist()
df

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

In [25]:
# 4. Print the updated DataFrame
df

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

When you're working with a dataset, you often want to break it into groups and then calculate some statistics within each group. That’s exactly what groupby() lets you do.

Imagine you have a big table of sales data. You want to know:

What’s the total revenue per region?
What’s the average sale price per salesperson?
How many products were sold per category?
All of these are grouped calculations — and Pandas makes them easy.

In [ ]:
df.groupby('column_to_group_by')['column_to_aggregate'].agg_function()

In [ ]:
# Average salary per Department
df.groupby('Department')['Salary'].mean()
#  Average salary by Department and Role
df.groupby(['Department', 'Role'])['Salary'].mean()

So far, we’ve seen how .groupby() can be used to group rows by a category and calculate a single summary statistic — like .mean().

That’s a great start! But real-world analysis often requires more than one summary at a time — maybe you want to see both the average and the total, or the count and the maximum, or even different stats for different columns.

That’s where .agg() comes in.

.agg() (short for aggregate) lets you:

Apply multiple functions at once
Specify different functions for different columns
Add custom labels to make the results easier to read

In [13]:
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Sales', 'Sales'],
    'Salary': [50000, 52000, 60000, 63000, 45000, 47000],
    'Tenure': [2, 3, 5, 4, 1, 2]
}
df = pd.DataFrame(df)

# Group by Department, get average and max salary
df.groupby('Department')['Salary'].agg(['mean', 'max'])

               mean    max
Department
HR          51000.0  52000
IT          61500.0  63000
Sales       46000.0  47000

Let’s say you want to find the mean Salary and the max Tenure for each department. You can use dictionaries within .agg():

In [14]:
df.groupby('Department').agg({
    'Salary': 'mean',
    'Tenure': 'max'
})

             Salary  Tenure
Department
HR          51000.0       3
IT          61500.0       5
Sales       46000.0       2

You can also rename the output columns to make them more readable using .agg() with tuples:

In [16]:
df.groupby('Department').agg(
    Avg_Salary=('Salary', 'mean'),
    Max_Tenure=('Tenure', 'max')
)

            Avg_Salary  Max_Tenure
Department
HR             51000.0           3
IT             61500.0           5
Sales          46000.0           2

In [17]:
data = {
    'Store': ['A', 'A', 'A', 'B', 'B', 'C', 'C', 'C', 'C'],
    'Product': ['Apples', 'Oranges', 'Bananas', 'Apples', 'Bananas', 'Oranges', 'Apples', 'Bananas', 'Bananas'],
    'Sales': [100, 80, 90, 120, 110, 60, 95, 85, 75],
    'Profit': [30, 25, 20, 40, 35, 15, 32, 22, 18]
}

df = pd.DataFrame(data)

# View the first few rows
print(df.head())

  Store  Product  Sales  Profit
0     A   Apples    100      30
1     A  Oranges     80      25
2     A  Bananas     90      20
3     B   Apples    120      40
4     B  Bananas    110      35

In [28]:
# 1. Group the data by Store and use .agg() to find the average Sales and average Profit for each store
df.groupby('Store').agg({
    'Sales' : 'mean',
    'Profit' : 'mean'
})

        Sales  Profit
Store
A       90.00   25.00
B      115.00   37.50
C       78.75   21.75

In [ ]:
# 2. Group by Product and get the maximum Sales and minimum Profit
df.groupby('Product')({
    'Sales' : 'max'
    'Profit' : 'min'
})

SyntaxError: invalid syntax (3996449123.py, line 4)

In [ ]:
# 3. Group by Store and return both the average Sales and maximum Profit, but name the columns 'Avg_Sales' and 'Max_Profit'

In [ ]:
# 4. BONUS: Group by both Store and Product, and find the total Sales using .agg()